name: 'delete-prereleases-for-branch'

description: 'An action to delete pre-releases for a specified branch'

inputs:
  github-token:
    description: 'A token with permission to delete releases in the repository.'
    required: true
  branch-name:
    description: 'The branch the releases were created for.'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
